parameters:
    planka_url: '%env(PLANKA_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/Planka/Exception/'
            - '../src/Shared/Exception/'
            - '../src/Kernel.php'

    App\Planka\Client\PlankaClient:
        arguments:
            $plankaUrl: '%planka_url%'

    App\Mcp\AttachmentTools:
        arguments:
            $uploadDir: '%kernel.project_dir%/var/uploads'
